/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectpackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Samadhidew
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pswlb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jUserField = new javax.swing.JTextField();
        Userlb = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        submitbtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pswlb.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        Pswlb.setForeground(new java.awt.Color(0, 0, 0));
        Pswlb.setText("Password");
        jPanel1.add(Pswlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("LOGIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 20));

        jUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jUserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 100, -1));

        Userlb.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        Userlb.setForeground(new java.awt.Color(0, 0, 0));
        Userlb.setText("User Name");
        jPanel1.add(Userlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, 20));

        submitbtn.setBackground(new java.awt.Color(204, 204, 255));
        submitbtn.setForeground(new java.awt.Color(0, 0, 0));
        submitbtn.setText("ADMIN");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 80, 20));

        submitbtn1.setBackground(new java.awt.Color(255, 204, 255));
        submitbtn1.setForeground(new java.awt.Color(0, 0, 0));
        submitbtn1.setText("Member");
        submitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(submitbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserFieldActionPerformed
       jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jUserFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jUserField.setText("");
        jPasswordField.setText("");
        jUserField.requestFocus();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        String un = jUserField.getText();
        String pw = String.valueOf(jPasswordField.getPassword());
        
        try{
           Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/LibraryDB", "APP", "123");
           Statement stmt = con.createStatement();
           ResultSet rst = stmt.executeQuery("SELECT *From LOGIN");
   ;
      
           while(rst.next()){
               String u = rst.getString("USERNAME");
               String p = rst.getString("PASSWORD");
               System.out.println(u+"\t"+p);
               
               if(un.equalsIgnoreCase(u)){
                   if(pw.equals(p)){
                       new LanguageGUI().setVisible(true);
                       this.setVisible(false);
                       break;
                   }
               }
           }
          
           
        }catch(Exception e){
            System.out.println(e.getMessage());
        
        }
      
    }//GEN-LAST:event_submitbtnActionPerformed

    private void submitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn1ActionPerformed
            String un = jUserField.getText();
        String pw = String.valueOf(jPasswordField.getPassword());
        
        try{
           Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/LibraryDB", "APP", "123");
           Statement stmt = con.createStatement();
           ResultSet rst = stmt.executeQuery("SELECT *From LOGIN");
   ;
      
           while(rst.next()){
               String usn = rst.getString("USERNAME");
               String p = rst.getString("PASSWORD");
               System.out.println(usn+"\t"+p);
               
               if(un.equalsIgnoreCase("dew")){
                   if(pw.equals("123")){
                       new MemberGUI("dew").setVisible(true);
                       this.setVisible(false);
                       break;
                   }
               }
           }
          
           
        }catch(Exception e){
            System.out.println(e.getMessage());
        
        }
            
    }//GEN-LAST:event_submitbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pswlb;
    private javax.swing.JLabel Userlb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jUserField;
    private javax.swing.JButton submitbtn;
    private javax.swing.JButton submitbtn1;
    // End of variables declaration//GEN-END:variables
}
